### ISSUE TITLE
Error durante la operación de firma del proveedor FNMT-RCM: La URL de destino final no puede ser nula

### ISSUE THREAD

**Issue by geralt** [ctt-gob-es/fire#6]
Buenos días,

probando el uso del conector de la FNMT, en una instalación de FIRe 2.3, que firma correctamente con el conector local (usando Autofirma), con un usuario válido en el entorno de PRE de CloudID de la FNMT, al intentar firmar un documento, tras seleccionar el certificado del CloudID sale el siguiente error:

> Error 201
> Error durante la operación de firma del proveedor FNMT-RCM. Pulse el botón Volver para seleccionar otro proveedor.

Si miro en el fichero log veo esto:

```
SEVERE: Error en la carga de datos: java.lang.IllegalArgumentException: La URL de destino final no puede ser nula
java.lang.IllegalArgumentException: La URL de destino final no puede ser nula
        at es.fnmt.fire.signature.connector.TrustedXRestHelper.createTripleRedirectionUrl(TrustedXRestHelper.java:520)
        at es.fnmt.fire.signature.connector.TrustedXConnector.loadDataToSign(TrustedXConnector.java:173)
        at es.gob.fire.server.services.internal.PreSignService.service(PreSignService.java:362)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```
¿**A qué URL se refiere el error**? Por si interesa, sí tengo desplegado el servicio de gestión de redirecciones (que se indica en el fichero provider_fnmt.properties)

Gracias por la ayuda.

**Comment by Gamuci** [comment]
Hola Geralt,

Revisando el código del conector he encontrado un problema por el cual no se carga correctamente el parámetro "redirectOkUrl" con el que se configura la URL a la que redirigir cuando termina correctamente la operación de firma. En su lugar se debe estar cargando otro llamado "redirectUrl".

Cuando configures la operación de firma o firma de lote, configura ambos parámetros ("redirectOkUrl" y "redirectUrl") con la URL a la que redirigir en caso de éxito. Así debe funcionar independientemente de que se utilice el proveedor local o el de la FNMT.

Un saludo.
